site_name: Mutuca
repo_url: https://github.com/dvths/mutuca
repo_name: mutuca
edit_uri: tree/main/docs
theme:
  palette:
    scheme: slate
    primary: teal
    accent: cyan
  features:
    - header.autohide
  name: material
  language: pt-BR
  logo: assets/mutuca-darktheme.png
  favicon: assets/mutuca-darktheme.png
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - attr_list
extra_css:
  - assets/stylesheets/extra.css
plugins:
  - mkdocs-jupyter
nav:
  - Home: index.md
  - Visão Geral:
      - Introdução ao Projeto: overview/introducao.md
      - Objetivos do Projeto: overview/objetivos.md
  - Arquitetura de Dados:
      - Visão Arquitetural: arquitetura/visao_arquitetural.md
      - Tecnologias Utilizadas: arquitetura/tecnologias.md
      - Fluxo de Dados: arquitetura/fluxo_dados.md
  - Pipeline de Dados:
      - Fontes e Estratégias: pipelines/fontes.md
      - Esquemas e Relacionamentos: pipelines/relacionamentos.md
  - Modelos de Dados:
      - Dicionários de Dados: momelos/dicionarios.md
      - Esquemas e Relacionamentos: modelos/esquemas.md
  - Execução Local:
      - Instalação e Setup: execucao_local/setup.md
      - Variáveis de Ambiente: execucao_local/variaveis.md
  - Orquestração:
      - Agendamento de Tarefas: orquestracao/agendamentos.md
      - Ferramentas: orquestracao/ferramentas.md
  - Boas Práticas:
      - Estilo de código: boas_praticas/codigo.md
      - Logs e versionamento: boas_praticas/logs_versionamento.md
  - Contribuições:
      - Como Contribuir: contribuicoes/guia.md
      - Fluxo de PRs: contribuicoes/pull_requests.md
  - Referências Legais:
      - LAI e LCP 131/2009: referencias/leis.md
  - Documentação da API:
      - Visão Geral: api/index.md
      - Modulo Principal: api/mutuca.md
  - FAQ: faq.md
  - Tutoriais:
      - prefeitura_municipal/contratos_licitacoes.ipynb
      - prefeitura_municipal/obras_publicas.ipynb
      - prefeitura_municipal/receitas.ipynb
