[project]
name = "mutuca"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google-api-python-client>=2.147.0",
    "google-auth>=2.35.0",
    "google-auth-httplib2>=0.2.0",
    "google-auth-oauthlib>=1.2.1",
    "requests>=2.32.3",
    "scrapy>=2.11.2",
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.5.39",
    "mkdocs-jupyter>=0.25.0",
    "oci>=2.142.0",
    "python-dotenv>=1.0.1",
    "pandas>=2.3.2",
    "python-json-logger>=2.0.7",
    "brotli>=1.2.0",
    "boto3>=1.42.39",
    "botocore>=1.42.39",
]

[tool.uv]
dev-dependencies = [
    "jupyterlab>=4.2.5",
    "black>=24.8.0",
    "isort>=5.13.2",
    "pdfplumber>=0.11.4",
    "pip>=24.2",
    "python-dotenv>=1.0.1",
    "ipdb>=0.13.13",
    "pytest>=9.0.3",
]
